/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package server;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Florian
 */
public class Console extends javax.swing.JFrame {
private SimpleDateFormat sdf;
    /**
     * Creates new form Console2
     */
    public Console() {
        initComponents();
        
        this.setVisible(false);
        this.setTitle("Chat-Server");
        this.setVisible(true);
        this.guiConsole.setText("Chat-Server");
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                Console.this.dispose();
            }
        });
        
        /* Simple Date Format */
        this.sdf = new SimpleDateFormat("hh:mm:ss");
    }
    
    
        public void log(String msg) {
        guiConsole.append("\n" + sdf.format(new Date()) + " : " + msg);
        if (guiAutoscroll.isSelected()) {
            guiConsole.setCaretPosition(guiConsole.getDocument().getLength());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiScroll = new javax.swing.JScrollPane();
        guiConsole = new javax.swing.JTextArea();
        guiAutoscroll = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guiConsole.setColumns(20);
        guiConsole.setRows(5);
        guiScroll.setViewportView(guiConsole);

        guiAutoscroll.setSelected(true);
        guiAutoscroll.setText("Autoscroll");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(guiAutoscroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guiAutoscroll))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox guiAutoscroll;
    private javax.swing.JTextArea guiConsole;
    private javax.swing.JScrollPane guiScroll;
    // End of variables declaration//GEN-END:variables
}
