/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Florian
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat2
     */
    public Chat() {
        initComponents();
        
        /* Window */
        this.setVisible(false);
        this.setTitle("Chat-Client");

        /* Center */
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        /* Show */
        this.setVisible(true);
    }
    
   public void addOutput(String message) {
        guiOutput.append(message + "\n");
    }

    public JButton getSend() {
        return guiSend;
    }

    public JTextArea getList() {
        return guiList;
    }

    public JTextField getInput() {
        return guiInput;
    }

    public String getText() {
        return this.getInput().getText();
    }

    public JTextArea getOutput() {
        return guiOutput;
    }

    public JButton getBye() {
        return guiBye;
    }

    public void setUsers(String users) {
        this.guiList.setText(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiListScroll = new javax.swing.JScrollPane();
        guiList = new javax.swing.JTextArea();
        guiOutputScroll = new javax.swing.JScrollPane();
        guiOutput = new javax.swing.JTextArea();
        guiInput = new javax.swing.JTextField();
        guiSend = new javax.swing.JButton();
        guiBye = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guiList.setColumns(20);
        guiList.setRows(5);
        guiListScroll.setViewportView(guiList);

        guiOutput.setColumns(20);
        guiOutput.setRows(5);
        guiOutputScroll.setViewportView(guiOutput);

        guiSend.setText("Send");

        guiBye.setText("Bye");
        guiBye.setName("guiBye"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guiInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiBye))
                    .addComponent(guiOutputScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guiOutputScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiSend)
                            .addComponent(guiBye)))
                    .addComponent(guiListScroll))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiBye;
    private javax.swing.JTextField guiInput;
    private javax.swing.JTextArea guiList;
    private javax.swing.JScrollPane guiListScroll;
    private javax.swing.JTextArea guiOutput;
    private javax.swing.JScrollPane guiOutputScroll;
    private javax.swing.JButton guiSend;
    // End of variables declaration//GEN-END:variables
}
